name: Deploy to EC2 (prod)

on:
  push:
    branches: ["prod"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # push to GHCR
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & tag image (lowercase repo)
        run: |
          REPO_LC=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          IMAGE="ghcr.io/${REPO_LC}:prod"
          SHA_IMAGE="ghcr.io/${REPO_LC}:${{ github.sha }}"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          echo "SHA_IMAGE=$SHA_IMAGE" >> $GITHUB_ENV
          docker build -t "$IMAGE" .
          docker tag "$IMAGE" "$SHA_IMAGE"

      - name: Push image
        run: |
          docker push "$IMAGE"
          docker push "$SHA_IMAGE"
      

      - name: SSH deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}          # ec2-54-162-139-200.compute-1.amazonaws.com
          username: ${{ secrets.EC2_USER }}      # admin (your Debian box)
          key: ${{ secrets.EC2_SSH_KEY }}        # contents of DPKeyPair.pem
          script: |
            set -e
            cd /opt/hotel-backend
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker compose pull
            docker compose up -d
            docker image prune -f
